<?php

declare(strict_types=1);

namespace TalanHdf\SemanticSuggestion\Upgrades;

use TYPO3\CMS\Core\Database\ConnectionPool;
use TYPO3\CMS\Core\Site\SiteFinder;
use TYPO3\CMS\Core\Utility\GeneralUtility;
use TYPO3\CMS\Install\Updates\DatabaseUpdatedPrerequisite;
use TYPO3\CMS\Install\Updates\UpgradeWizardInterface;

/**
 * Splits the old root_page_id column into root_page_id + scope_page_id.
 *
 * Until v4.0, root_page_id stored the scheduler task's startPageId, whatever page
 * that was, so a task run on a subtree produced a row set that looked like a site
 * but was not one. Site-scoped queries could not rely on it (see #23).
 *
 * This wizard rewrites existing rows so that:
 *   - scope_page_id keeps the old value (the task's starting page)
 *   - root_page_id  holds the real site root that page belongs to
 */
class MigrateRootPageIdUpgradeWizard implements UpgradeWizardInterface
{
    private const TABLE = 'tx_semanticsuggestion_similarities';

    public function getIdentifier(): string
    {
        return 'semanticSuggestionMigrateRootPageId';
    }

    public function getTitle(): string
    {
        return 'Semantic Suggestion: split root_page_id into site root and analysis scope';
    }

    public function getDescription(): string
    {
        return 'Existing similarity rows store the scheduler task startPageId in root_page_id. '
            . 'This wizard moves that value to the new scope_page_id column and fills root_page_id '
            . 'with the real site root, so that frontend suggestions can be scoped per site. '
            . 'Rows whose page no longer belongs to a configured site are left untouched and should '
            . 'be regenerated by re-running the scheduler task.';
    }

    public function getPrerequisites(): array
    {
        return [DatabaseUpdatedPrerequisite::class];
    }

    public function updateNecessary(): bool
    {
        return $this->countUnmigratedRows() > 0;
    }

    public function executeUpdate(): bool
    {
        $connectionPool = GeneralUtility::makeInstance(ConnectionPool::class);
        $siteFinder = GeneralUtility::makeInstance(SiteFinder::class);

        // Snapshot the distinct legacy values before touching anything: root_page_id is
        // rewritten below and one group's new value may collide with another group's
        // old value.
        $queryBuilder = $connectionPool->getQueryBuilderForTable(self::TABLE);
        $legacyScopeIds = $queryBuilder
            ->select('root_page_id')
            ->from(self::TABLE)
            ->where($queryBuilder->expr()->eq('scope_page_id', 0))
            ->groupBy('root_page_id')
            ->executeQuery()
            ->fetchFirstColumn();

        foreach ($legacyScopeIds as $legacyScopeId) {
            $legacyScopeId = (int)$legacyScopeId;

            // 0 was never a valid startPageId and cannot be resolved to a site; such
            // rows are ambiguous by construction and are left for a task re-run.
            if ($legacyScopeId <= 0) {
                continue;
            }

            try {
                $realRootPageId = $siteFinder->getSiteByPageId($legacyScopeId)->getRootPageId();
            } catch (\Exception $e) {
                continue;
            }

            $updateQueryBuilder = $connectionPool->getQueryBuilderForTable(self::TABLE);
            $updateQueryBuilder
                ->update(self::TABLE)
                ->set('scope_page_id', $legacyScopeId)
                ->set('root_page_id', $realRootPageId)
                ->where(
                    $updateQueryBuilder->expr()->eq(
                        'root_page_id',
                        $updateQueryBuilder->createNamedParameter($legacyScopeId)
                    ),
                    $updateQueryBuilder->expr()->eq('scope_page_id', 0)
                )
                ->executeStatement();
        }

        return true;
    }

    private function countUnmigratedRows(): int
    {
        $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
            ->getQueryBuilderForTable(self::TABLE);

        return (int)$queryBuilder
            ->count('uid')
            ->from(self::TABLE)
            ->where($queryBuilder->expr()->eq('scope_page_id', 0))
            ->executeQuery()
            ->fetchOne();
    }
}
