<?php

return [
    "français" => ["le", "la", "les", "de", "des", "du", "et", "à", "en", "un", "une", "dans", "pour", "sur", "est", "sont", "ce", "cette", "ces", "qui", "que", "quoi", "dont", "avec", "sans", "mais", "ou", "si", "car", "comme", "parce que", "donc", "alors", "pendant", "avant", "après", "sous", "entre", "depuis", "vers", "jusque", "contre", "environ", "selon", "devant", "derrière", "dessus", "dessous", "loin", "près", "autour", "ici", "là", "ailleurs", "aujourd'hui", "hier", "demain", "jamais", "toujours", "encore", "déjà", "beaucoup", "peu", "plus", "moins", "assez", "trop", "très", "même", "aussi", "autre", "tel", "quel", "certain", "chaque", "plusieurs", "quelques", "aucun", "tout", "tous", "toutes", "rien", "personne", "on", "il", "elle", "ils", "elles", "je", "tu", "nous", "vous", "se", "son", "sa", "ses", "leur", "leurs", "mon", "ma", "mes", "ton", "ta", "tes", "notre", "nos", "votre", "vos", "y", "en", "ceci", "cela", "ça"],
    "espagnol" => ["el", "la", "los", "las", "de", "del", "y", "a", "en", "un", "una", "unos", "unas", "con", "para", "por", "es", "son", "está", "están", "fue", "fueron", "ser", "estar", "haber", "tener", "hacer", "decir", "poder", "ir", "venir", "ver", "saber", "querer", "dar", "pensar", "sentir", "creer", "entender", "encontrar", "llevar", "dejar", "empezar", "seguir", "terminar", "trabajar", "vivir", "morir", "nacer", "crecer", "aprender", "enseñar", "jugar", "ganar", "perder", "buscar", "encontrar", "comprar", "vender", "comer", "beber", "dormir", "despertar", "levantarse", "vestirse", "desvestirse", "ducharse", "bañarse", "afeitarse", "maquillarse", "peinarse", "cepillarse", "los dientes", "lavarse", "las manos", "la cara", "secarse", "el pelo", "el cuerpo", "ponerse", "los zapatos", "la ropa", "quitarse", "los zapatos", "la ropa", "acostarse", "dormirse", "soñar", "despertarse", "levantarse", "ir", "al baño", "a la escuela", "al trabajo", "a casa", "de compras", "de vacaciones", "de viaje", "en coche", "en autobús", "en tren", "en avión", "a pie", "en bicicleta", "hablar", "escribir", "leer", "escuchar", "ver", "mirar", "observar", "tocar", "sentir", "oler", "probar", "gustar", "amar", "odiar", "querer", "desear", "necesitar", "tener que", "deber", "poder", "saber", "conocer", "entender", "comprender", "aprender", "enseñar", "recordar", "olvidar", "pensar", "creer", "imaginar", "soñar", "sentir", "esperar", "querer", "desear", "necesitar", "tener que", "deber", "poder","saber", "conocer"],
    "anglais": ["the", "a", "an", "and", "in", "to", "of", "is", "are", "was", "were", "be", "been", "have", "has", "had", "do", "does", "did", "will", "would", "should", "can", "could", "may", "might", "must", "shall", "ought", "i", "me", "my", "mine", "we", "us", "our", "ours", "you", "your", "yours", "he", "him", "his", "she", "her", "hers", "it", "its", "they", "them", "their", "theirs", "this", "that", "these", "those", "all", "any", "both", "each", "few", "more", "most", "other", "some", "such", "no", "nor", "not", "only", "own", "same", "so", "than", "too", "very", "s", "t", "can", "will", "just", "don", "should", "now"],
    "allemand": ["der", "die", "das", "den", "dem", "des", "und", "in", "zu", "von", "ist", "sind", "war", "waren", "sei", "seien", "habe", "haben", "hatte", "hatten", "werde", "werden", "wird", "wirst", "würde", "würden", "soll", "sollen", "sollte", "solltest", "solltet", "kann", "können", "konnte", "konntest", "konntet", "muss", "müssen", "musste", "musstest", "musstet", "darf", "dürfen", "durfte", "durftest", "durftet", "mag", "mögen", "mochte", "mochtest", "mochtet", "ich", "mich", "mir", "mein", "meine", "meiner", "meines", "wir", "uns", "unser", "unsere", "unserer", "unseres", "du", "dich", "dir", "dein", "deine", "deiner", "deines", "ihr", "euch", "euer", "eure", "eurer", "eures", "er", "ihn", "ihm", "sein", "seine", "seiner", "seines", "sie", "ihr", "ihre", "ihrer", "ihres", "es", "ihm", "sein", "seine", "seiner", "seines", "dies", "dieser", "dieses", "diese", "jener", "jenes", "jene", "alles", "alle", "aller", "alles", "viele", "wenige", "mehr", "meiste", "andere", "einige", "solche", "kein", "keine", "keiner", "keines", "nur", "eigen", "selbst", "so", "auch", "sehr", "s", "t", "wollen", "können", "müssen", "sollen", "dürfen", "mögen", "haben", "sein", "werden", "lassen", "gehen", "kommen", "sehen", "wissen", "geben", "nehmen", "sagen", "machen", "stehen", "sitzen", "liegen", "finden", "bleiben", "halten", "bringen", "schreiben", "lesen", "sprechen", "hören", "spielen", "laufen", "arbeiten", "lernen", "essen", "trinken", "schlafen", "leben", "sterben"]
],

