services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'
      
  TalanHdf\SemanticSuggestion\Service\StopWordsService:
      public: true

  TalanHdf\SemanticSuggestion\Service\NlpApiService:
    public: true

  TalanHdf\SemanticSuggestion\Service\PageAnalysisService:
    arguments:
      $context: '@TYPO3\CMS\Core\Context\Context'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      $stopWordsService: '@TalanHdf\SemanticSuggestion\Service\StopWordsService'
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
      $extensionConfiguration: '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      $cacheManager: '@TYPO3\CMS\Core\Cache\CacheManager'
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'
    calls:
      - method: setNlpApiService
        arguments: ['@TalanHdf\SemanticSuggestion\Service\NlpApiService']




  TalanHdf\SemanticSuggestion\Controller\SuggestionsController:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $fileRepository: '@TYPO3\CMS\Core\Resource\FileRepository'

  TalanHdf\SemanticSuggestion\Controller\SemanticBackendController:
    public: true
    autowire: true
    autoconfigure: true
    tags: ['controller.backend_controller']
    arguments:
      $logManager: '@TYPO3\CMS\Core\Log\LogManager' 

  TYPO3\CMS\Core\Log\LogManager:
    public: true