services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'
      
  TalanHdf\SemanticSuggestion\Service\StopWordsService:
      public: true

  TalanHdf\SemanticSuggestion\Service\NlpApiService:
    public: true

  TalanHdf\SemanticSuggestion\Service\PageAnalysisService:
    public: true
    arguments:
      $context: '@TYPO3\CMS\Core\Context\Context'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManagerInterface'
      $stopWordsService: '@TalanHdf\SemanticSuggestion\Service\StopWordsService'
      $similarityCalculatorFactory: '@TalanHdf\SemanticSuggestion\Service\SimilarityCalculatorFactory'
      $siteFinder: '@TYPO3\CMS\Core\Site\SiteFinder'
      $nlpApiService: '@TalanHdf\SemanticSuggestion\Service\NlpApiService'
      $extensionConfiguration: '@TYPO3\CMS\Core\Configuration\ExtensionConfiguration'
      $cache: '@cache.semantic_suggestion'
      $cacheManager: '@TYPO3\CMS\Core\Cache\CacheManager'
      $connectionPool: '@TYPO3\CMS\Core\Database\ConnectionPool'

  TalanHdf\SemanticSuggestion\Service\SimilarityCalculatorFactory:
    public: true

  cache.semantic_suggestion:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['semantic_suggestion']

    
  TalanHdf\SemanticSuggestion\Controller\SuggestionsController:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $fileRepository: '@TYPO3\CMS\Core\Resource\FileRepository'

  TalanHdf\SemanticSuggestion\Controller\SemanticBackendController:
    public: true
    autowire: true
    autoconfigure: true
    tags: ['controller.backend_controller']
    arguments:
      $logManager: '@TYPO3\CMS\Core\Log\LogManager' 

  TYPO3\CMS\Core\Log\LogManager:
    public: true