services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'

  TalanHdf\SemanticSuggestion\Service\PageAnalysisService:
    arguments:
      $context: '@TYPO3\CMS\Core\Context\Context'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      $cacheManager: '@TYPO3\CMS\Core\Cache\CacheManager'
      $dbConnection: '@TYPO3\CMS\Core\Database\ConnectionPool'
    public: true

  TalanHdf\SemanticSuggestion\Controller\SuggestionsController:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $fileRepository: '@TYPO3\CMS\Core\Resource\FileRepository'

  TalanHdf\SemanticSuggestion\Controller\SemanticBackendController:
      public: true
      autowire: true
      autoconfigure: true
      tags: ['controller.backend_controller']