services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'

  TalanHdf\SemanticSuggestion\Service\NlpService:
    public: true

  TalanHdf\SemanticSuggestion\Service\PageAnalysisService:
    arguments:
      $context: '@TYPO3\CMS\Core\Context\Context'
      $configurationManager: '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      $nlpService: '@TalanHdf\SemanticSuggestion\Service\NlpService'
      $cacheManager: '@TYPO3\CMS\Core\Cache\CacheManager'
      $dbConnection: '@TYPO3\CMS\Core\Database\ConnectionPool'
    calls:
      - method: setLogger
        arguments: ['@TYPO3\CMS\Core\Log\LogManager']
    public: true

  TalanHdf\SemanticSuggestion\Controller\SuggestionsController:
    public: true
    arguments:
      $pageAnalysisService: '@TalanHdf\SemanticSuggestion\Service\PageAnalysisService'
      $fileRepository: '@TYPO3\CMS\Core\Resource\FileRepository'

  TalanHdf\SemanticSuggestion\Controller\SemanticBackendController:
    tags: ['backend.controller']

  TalanHdf\SemanticSuggestion\Command\NlpAnalysisCommand:
    tags:
      - name: 'console.command'
        command: 'semanticsuggestion:nlpanalysis'