services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TalanHdf\SemanticSuggestion\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  TalanHdf\SemanticSuggestion\Loader\LoaderInterface:
    class: TalanHdf\SemanticSuggestion\Loader\PageLoader

  TalanHdf\SemanticSuggestion\Analyzer\AnalyzerInterface:
    class: TalanHdf\SemanticSuggestion\Analyzer\ContentAnalyzer

  TalanHdf\SemanticSuggestion\Service\SemanticSuggestionService:
    public: true